name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:

        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

        dockerfile_directory: ./
        dockerfile_name: Dockerfile
        docker_options: "--no-cache"

        process_type: web
        


      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.8'  # Specify the Python version you need

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      
        
      #   dockerfile_directory: ./
      #   dockerfile_name: Dockerfile
      #   docker_options: "--no-cache"

      # - name: Run tests with verbose output
      #   run: |
      #     pytest -v  # Run tests with verbose output to see detailed results

      # - name: Deploy
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      #   run: |
      #     curl -v "$deploy_url"