name: RENDER

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest

      # - name: Run tests with collection only
      #   run: |
      #     pytest --collect-only  # See what pytest is trying to collect

      # - name: Deploy
      #   if: github.ref == 'refs/heads/main'
      #   env:
      #     deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      #   run: |
      #     curl "$deploy_url"

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploy URL: $deploy_url"  # Debugging step
          curl -v "$deploy_url"  # Add -v for verbose output to debug the curl request
