name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Add your test command here
        pytest

    - name: Build and deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Add your Render API key to GitHub secrets
      run: |
        # Install Render CLI
        curl -fsSL https://render.com/static/cli/render -o /usr/local/bin/render
        chmod +x /usr/local/bin/render

        # Deploy to Render
        render deploy <your-service-id> --env <environment>

